<h1>Quiz 1 - CMSC 197 Machine Learning</h1>
<h2>Hannah Bella C. Arceño</h2>

<h2>Import modules</h2>

In [1]:
# Import modules
import numpy as np
import math

<h1 style='color: blue'>Part 1</h1>

<h2>1. Creation and initialization of 'y_hat' and 'y' arrays</h2>

In [2]:
y_hat = np.linspace(-1, 1, 20, endpoint=True)
y = np.linspace(0, 1, 20, endpoint=True)

In [3]:
y_hat # Display y_hat array

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [4]:
y # Display y array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<h2>2. Shape and dimension of 'y_hat' and 'y'</h2>

In [5]:
print(f"'y_hat' array\nshape:\t{y_hat.shape} \ndimension:\t{y_hat.ndim}")

'y_hat' array
shape:	(20,) 
dimension:	1


In [6]:
print(f"'y' array\nshape:\t{y.shape} \ndimension:\t{y.ndim}")

'y' array
shape:	(20,) 
dimension:	1


<h2>3. Loss Functions</h2>

<h3>Mean Square Error (MSE)</h3>

In [7]:
def get_mean_square_error(y_hat, y):
    n =  min(y_hat.shape[0], y.shape[0])
    square_err = 0
    
    for i in range(n):
        square_err += (y_hat[i] - y[i])**2
        
    return square_err/n


print('L = ', get_mean_square_error(y_hat, y))

L =  0.34210526315789475


<h3>Mean Absolute Error (MAE)</h3>

In [8]:
def get_mean_absolute_error(y_hat, y):
    n =  min(y_hat.shape[0], y.shape[0])
    absolute_err = 0
    
    for i in range(n):
        absolute_err += abs(y_hat[i] - y[i])
        
    return absolute_err/n


print('L = ', get_mean_absolute_error(y_hat, y))

L =  0.5000000000000001


<h3>Mean Squared Logarithmic Error (MSLE)</h3>

In [9]:
def get_mean_squared_logarithmic_error(y_hat, y):
    n =  min(y_hat.shape[0], y.shape[0])
    squared_logarithmic_err = 0
    
    for i in range(n):
        try: 
            squared_logarithmic_err += (math.log(y_hat[i] + 1) - math.log(y[i] + 1))**2
            
        except ValueError:
            return "undefined" # When a 'y_hat' or 'y' value is negative or zero value
            # We cannot calculate natural log. of a negative or zero-valued number
        
    return squared_logarithmic_err/n


print('L = ', get_mean_squared_logarithmic_error(y_hat, y))

L =  undefined


<h3>Mean Absolute Percentage Error (MAPE)</h3>

In [10]:
def get_mean_absolute_percentage_error(y_hat, y):
    n =  min(y_hat.shape[0], y.shape[0])
    absolute_err = 0
    
    for i in range(n):
        try:
            absolute_err += abs((y_hat[i] - y[i])/y[i]) 
            
        except:
            return "undefined" # MAPE cannot be calculated if a 'y' value is zero (0).
        
    return (absolute_err/n) * 100


print('L (in %)= ', get_mean_absolute_percentage_error(y_hat, y))

L (in %)=  inf


C:\Users\User\AppData\Local\Temp\ipykernel_1396\3356021675.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  absolute_err += abs((y_hat[i] - y[i])/y[i])


<h1 style='color: blue'>Part 2</h1>

<h2>1. Create a 1d array M {1, 2, …16} using the arange function</h2>

In [11]:
M = np.arange(1, 17)
M # Display M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

<h2>2. Reshape M into 4x4 array and store it to N</h2>

In [12]:
N = M.reshape(4,4)
N # Display 2d array N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<h2>3. Get the 2nd row of N</h2>

In [13]:
N[1]

array([5, 6, 7, 8])

<h2>4. Get the minimum values for each column of N</h2>

In [14]:
np.min(N, axis=0)

array([1, 2, 3, 4])

<h2>5. Get the locations of the minimum values for each column of N</h2>

In [15]:
np.argmin(N, axis=0) # Location in each column

array([0, 0, 0, 0], dtype=int64)

In [16]:
# Another solution: Location coordinates (in the matrix) of the minimum values for each column of N

col_min = np.min(N, axis = 0) # Array containing minimum values for each column of N
location_min = [] # Array that will contain index location of minimum values for each column of N

location_coordinates = [] # Location of minimum values in the matrix

for i in range(col_min.size):
    location_min.append(np.where(N == col_min[i]))
    
for i in range(len(location_min)):
    location_coordinates.append((location_min[i][0][0], location_min[i][1][0]))
    
location_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

<h2>6. Get the average of the whole matrix</h2>

In [17]:
np.mean(N)

8.5

<h2>7. Create a vector V with 4 elements, each element is 1</h2>

In [18]:
V = np.ones((4), dtype='int32')
V

array([1, 1, 1, 1])

<h2>8. Take the dot product of N and V</h2>

In [19]:
np.dot(N,V)

array([10, 26, 42, 58])